// ============================================================
// Forge — Build Intelligence: blueprint generators
// ============================================================
// Phase 1 "zero touch": once the analyzer knows what a project can
// become, the blueprint writes the actual configuration:
//
//   action "export-mode"   — patch next.config.* with a BUILD_APK
//                            env toggle (opt-in static export)
//   action "capacitor"     — scaffold capacitor.config.ts
//   action "apk-workflow"  — generate .github/workflows/forge-apk.yml
//   action "all"           — everything above
//
// All writes stay inside the project workspace. Existing files are
// backed up to .forge-backups/ before modification, and nothing is
// overwritten silently — every change is reported to the caller.
// ============================================================

import * as fs from 'node:fs';
import * as path from 'node:path';
import type { ProjectAnalysis } from './analyzer';

export type BlueprintAction = 'export-mode' | 'capacitor' | 'apk-workflow' | 'all';

export interface BlueprintChange {
  action: BlueprintAction | 'backup';
  file: string;
  status: 'written' | 'patched' | 'backed-up' | 'skipped';
  reason?: string;
}

export interface BlueprintResult { ok: boolean; changes: BlueprintChange[]; error?: string }

function rel(root: string, full: string): string {
  return path.relative(root, full).split(path.sep).join('/');
}

function ensureParent(file: string): void {
  fs.mkdirSync(path.dirname(file), { recursive: true });
}

function backup(root: string, full: string, changes: BlueprintChange[]): void {
  if (!fs.existsSync(full)) return;
  const backupDir = path.join(root, '.forge-backups');
  fs.mkdirSync(backupDir, { recursive: true });
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const target = path.join(backupDir, `${path.basename(full)}.${stamp}.bak`);
  fs.copyFileSync(full, target);
  changes.push({ action: 'backup', file: rel(root, target), status: 'backed-up' });
}

function patchNextConfig(root: string, analysis: ProjectAnalysis, changes: BlueprintChange[]): void {
  const name = analysis.nextConfig.file ?? 'next.config.ts';
  const full = path.join(root, name);

  if (!fs.existsSync(full)) {
    const isTs = name.endsWith('.ts');
    const content = isTs
      ? `import type { NextConfig } from 'next';

// Generated by Forge Build Intelligence.
const nextConfig: NextConfig = {
  output: process.env.BUILD_APK === '1' ? 'export' : undefined,
  images: { unoptimized: process.env.BUILD_APK === '1' },
};

export default nextConfig;
`
      : `/** @type {import('next').NextConfig} */
const nextConfig = {
  output: process.env.BUILD_APK === '1' ? 'export' : undefined,
  images: { unoptimized: process.env.BUILD_APK === '1' },
};

module.exports = nextConfig;
`;
    ensureParent(full);
    fs.writeFileSync(full, content);
    changes.push({ action: 'export-mode', file: name, status: 'written', reason: 'created with BUILD_APK toggle' });
    return;
  }

  const raw = fs.readFileSync(full, 'utf8');
  if (/BUILD_APK/.test(raw)) {
    changes.push({ action: 'export-mode', file: name, status: 'skipped', reason: 'BUILD_APK toggle already present' });
    return;
  }

  backup(root, full, changes);
  let patched: string | null = null;

  if (/output\s*:\s*['"][a-z-]+['"]/.test(raw)) {
    patched = raw.replace(
      /output\s*:\s*['"]([a-z-]+)['"]/,
      (_m, val: string) => `output: process.env.BUILD_APK === '1' ? 'export' : '${val}'`,
    );
  } else {
    const objMatch = raw.match(/const\s+\w*[Cc]onfig\w*\s*(?::\s*[^=]+)?=\s*\{/);
    if (objMatch && objMatch.index !== undefined) {
      const insertAt = objMatch.index + objMatch[0].length;
      const injection = `\n  output: process.env.BUILD_APK === '1' ? 'export' : undefined,\n  images: { unoptimized: process.env.BUILD_APK === '1' },`;
      patched = raw.slice(0, insertAt) + injection + raw.slice(insertAt);
    }
  }

  if (!patched) {
    changes.push({ action: 'export-mode', file: name, status: 'skipped', reason: 'could not safely patch — apply manually' });
    return;
  }
  if (!/unoptimized/.test(patched)) {
    patched = patched.replace(
      /(output\s*:\s*process\.env\.BUILD_APK[^\n]*\n)/,
      `$1  images: { unoptimized: process.env.BUILD_APK === '1' },\n`,
    );
  }
  fs.writeFileSync(full, patched);
  changes.push({ action: 'export-mode', file: name, status: 'patched', reason: 'BUILD_APK toggle inserted (backup saved)' });
}

function scaffoldCapacitor(root: string, analysis: ProjectAnalysis, changes: BlueprintChange[]): void {
  const full = path.join(root, 'capacitor.config.ts');
  if (fs.existsSync(full)) {
    changes.push({ action: 'capacitor', file: 'capacitor.config.ts', status: 'skipped', reason: 'already exists' });
    return;
  }
  const appName = analysis.packageName?.replace(/^@[^/]+\//, '') ?? 'ForgeApp';
  const title = appName.charAt(0).toUpperCase() + appName.slice(1);
  const content = `import type { CapacitorConfig } from '@capacitor/cli';

// Generated by Forge Build Intelligence.
// The static export (BUILD_APK=1) lands in ./out and is bundled into
// the native shell by \`npx cap sync\`.
const config: CapacitorConfig = {
  appId: '${analysis.appIdSuggestion}',
  appName: '${title}',
  webDir: 'out',
  server: { androidScheme: 'https' },
};

export default config;
`;
  ensureParent(full);
  fs.writeFileSync(full, content);
  changes.push({ action: 'capacitor', file: 'capacitor.config.ts', status: 'written' });
}

function generateApkWorkflow(root: string, analysis: ProjectAnalysis, changes: BlueprintChange[]): void {
  const dir = path.join(root, '.github', 'workflows');
  const full = path.join(dir, 'forge-apk.yml');
  if (fs.existsSync(full)) {
    changes.push({ action: 'apk-workflow', file: rel(root, full), status: 'skipped', reason: 'already exists' });
    return;
  }
  const useBun = analysis.packageManager === 'bun';
  const installCmd = useBun ? 'bun install --frozen-lockfile' : 'npm ci';
  const runPrefix = useBun ? 'bun' : 'npm run';
  const buildCmd = analysis.scripts.build ? `${runPrefix} build` : `${runPrefix} build || npx next build`;
  const bunSetup = useBun ? `
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
` : '';
  const toolingCmd = useBun
    ? 'bun add -d @capacitor/cli && bun add @capacitor/core @capacitor/android'
    : 'npm i -D @capacitor/cli && npm i @capacitor/core @capacitor/android';

  const yml = `# Generated by Forge Build Intelligence.
# Builds an offline Android APK from the static export and uploads it
# as a workflow artifact. Free on public repositories.
name: Forge APK

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
${bunSetup}
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-\${{ hashFiles('android/**/*.gradle*', 'android/**/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Install dependencies
        run: ${installCmd}

      - name: Install Capacitor tooling
        run: ${toolingCmd}

      - name: Static export (BUILD_APK=1)
        run: ${buildCmd}
        env:
          BUILD_APK: '1'

      - name: Capacitor add + sync
        run: |
          npx cap add android || true
          npx cap sync android

      - name: Build APK
        working-directory: android
        run: ./gradlew assembleDebug --no-daemon

      - name: Collect artifact
        run: |
          mkdir -p apk-out
          cp android/app/build/outputs/apk/debug/app-debug.apk apk-out/forge-app-\${{ github.sha }}.apk 2>/dev/null || \
          cp android/app/build/outputs/apk/debug/*.apk apk-out/forge-app.apk

      - uses: actions/upload-artifact@v4
        with:
          name: forge-apk
          path: apk-out/*.apk
          retention-days: 90
`;
  ensureParent(full);
  fs.writeFileSync(full, yml);
  changes.push({ action: 'apk-workflow', file: rel(root, full), status: 'written' });
}

export function applyBlueprint(root: string, analysis: ProjectAnalysis, action: BlueprintAction): BlueprintResult {
  const changes: BlueprintChange[] = [];
  try {
    const resolved = path.resolve(root);
    if (!fs.existsSync(resolved) || !fs.statSync(resolved).isDirectory()) {
      return { ok: false, changes, error: 'Workspace not found' };
    }
    const doExport = action === 'export-mode' || action === 'all';
    const doCap = action === 'capacitor' || action === 'all';
    const doWf = action === 'apk-workflow' || action === 'all';

    if (doExport) {
      if (analysis.framework !== 'next') {
        changes.push({ action: 'export-mode', file: 'next.config.*', status: 'skipped', reason: `framework is ${analysis.framework}, not next` });
      } else {
        patchNextConfig(root, analysis, changes);
      }
    }
    if (doCap) scaffoldCapacitor(root, analysis, changes);
    if (doWf) generateApkWorkflow(root, analysis, changes);
    return { ok: true, changes };
  } catch (err) {
    return { ok: false, changes, error: err instanceof Error ? err.message : String(err) };
  }
}
